services:
  whoami-tcp:
    #image: teebow1e/whoami-tcp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "nc -z -w 5 localhost 8080 && echo 'test' | nc -w 5 localhost 8080 | grep -q '.' || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
